### ISSUE TITLE
Which protobuf version is used ? Latest 3.15.1 does not compile

### ISSUE THREAD

**Issue by costaverde** [vinifr/ctraderOpenAPI#1]
With protobuf 3.15.1 (latest), compile error "This file was generated by an older version of protocolbuffer".

**Comment by vinifr** [comment]
Looks like you need to generate the pb.cc and pb.h files and replace over the old ones.

**Comment by vinifr** [comment]
Check this: https://github.com/vinifr/ctraderOpenAPI#generating-c-files-from-protobuf

Let me know if solve the issue.

**Comment by OmerTurann** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
harryEth, @YohannHommet, @dnorange, @Ansbubble, @sikusk199, @Winnaries, @humayunk, @Kalyanimhala, @Jaxiii, @felipechang, @brandon-o, @Vanneldas22, @Badrdine, @thomasza92, @panda850819, @ikowin, @qrxnz, @gqf2008, @jianxiutou5, @antronyx
